# Фильмы
## Получить список фильмов

GET http://localhost:4000/films HTTP/1.1
Content-Type: application/json

###

###

## Получить детальную инфу по фильму

GET http://localhost:4000/films/63e0f65023190ca3ebe5c095/details HTTP/1.1


###

##Получить список фильмов определённого жанра
GET http://localhost:4000/genres/63de171e72503699e9e192cd/films?limit=3 HTTP/1.1

###
## Создать новый фильм

POST http://localhost:4000/films HTTP/1.1
Content-Type: application/json

{
  "title": "sdfsdjjjjasd32323",
  "description": "asdasdnfdhgfdhgdhgdhgdhgchtdh",
  "postDate": "2003-01-10",
  "genres": ["qweqwefdfdffdfdf"],
  "releaseDate": "erer",
  "rating": 8,
  "previewVideo": "ererer",
  "video": "dfdf",
  "actors": ["klkl"],
  "director": "l;;l",
  "runTime": "zxzx",
  "poster": "qwqwqwqwq",
  "backgroundImg": "xcxcxcxc",
  "backgroundColor": "nmnmmn",
  "genres": ["63de171e72503699e9e192cd"],
  "userId": "63e0f68323190ca3ebe5c0a0"
}

###

## Обновить фильм

PATCH http://localhost:4000/films/dsfsdfsf HTTP/1.1
Content-Type: application/json

{
  "id": "63de2d37835d455ad5ea571a",
  "title": "длдлдлlklklkl",
  "description": "asdasdnfdhgfdhgdhgdhgdhgchtdh",
  "postDate": "2003-01-10",
  "genres": ["qweqwe"],
  "releaseDate": "erer",
  "rating": 8,
  "previewVideo": "ererer",
  "video": "dfdf",
  "actors": ["klkl"],
  "director": "l;;l",
  "runTime": "zxzx",
  "poster": "qwqwqwqwq",
  "backgroundImg": "xcxcxcxc",
  "bacgroundColor": "nmnmmn"
}



###

## Удалить фильм

DELETE http://localhost:4000/films/ghghfhfhhg HTTP/1.1
Content-Type: application/json

###

#Жанры
## Получить список жанров

GET http://localhost:4000/genres HTTP/1.1
Content-Type: application/json

###

## Создать новый жанр

POST http://localhost:4000/genres HTTP/1.1
Content-Type: application/json

{
  "name": "Actionjjgh"
}

###

# Пользователи

## Отправка аватарки пользователю

POST http://localhost:4000/users/63e0f68323190ca3ebe5c0a0/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/tmp/screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Регистрация пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlool.net",
  "avatarPath": "torrance.png",
  "name": "John",
  "password": "shining"
}

###

## Авторизация пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlool.net",
  "password": "shining"
}

###

## Проверка токена пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vbC5uZXQiLCJpZCI6IjYzZWJhMTMxYmFlNGEyZjllMmRjNDEzOCIsImlhdCI6MTY3NjM4OTE5MCwiZXhwIjoxNjc2NTYxOTkwfQ.pNgj3FxODP6RU5fpddd18R04Ixa2tC4v6_EaljoIaO0

###

#Комментарии
## Создать комментарий
POST http://localhost:4000/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Норм фильм",
  "filmId": "63e38cd3ce412cc72afbb2c7",
  "userId": "63e0f68323190ca3ebe5c0a0",
  "rating": 8
}

###
## Список комментариев к фильму
GET http://localhost:4000/films/63e38cd3ce412cc72afbb2c7/comments HTTP/1.1

###
